Clean old runs

diff --git a/.github/workflows/check-update.yaml b/.github/workflows/check-update.yaml
--- a/.github/workflows/check-update.yaml
+++ b/.github/workflows/check-update.yaml
@@ -62,3 +62,43 @@ jobs:
     with:
       version: ${{ needs.check-update.outputs.version }}
       repo: ${{ vars.TARGET_REPO }}
+
+  clean-history:
+    name: Clean History
+    needs: check-update
+    runs-on: ubuntu-latest
+    steps:
+      - name: Clean old run
+        env:
+          GH_TOKEN: ${{ github.token }}
+          REPOSITORY: ${{ github.repository }}
+        run: |
+          WORKFLOW_NAME='check-update.yaml'
+          JQ_OLD=".workflow_runs[] | select(.created_at | fromdateiso8601 < $(date -d 'last month' +%s)) | .id"
+          
+          echo "Getting all old runs for workflow $WORKFLOW_NAME in $REPOSITORY"
+
+          RUNS=$(
+            gh api \
+              -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              "/repos/$REPOSITORY/actions/workflows/$WORKFLOW_NAME/runs" \
+              --paginate \
+              --jq "$JQ_OLD"
+          )
+
+          echo "Found $(echo "$RUNS" | wc -l) old runs for workflow $WORKFLOW_NAME"
+
+          # Delete each run
+          for RUN in $RUNS; do
+            echo "Deleting run $RUN"
+            gh api \
+              --silent \
+              --method DELETE \
+              -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              "/repos/$REPOSITORY/actions/runs/$RUN" || echo "Failed to delete run $RUN"
+
+            # Sleep for 100ms to avoid rate limiting
+            sleep 0.1
+          done
